
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GE = 15;
  public static final int SM = 23;
  public static final int CASE = 32;
  public static final int DECR = 28;
  public static final int INCR = 29;
  public static final int FOR = 27;
  public static final int MINUS = 3;
  public static final int LS = 17;
  public static final int LP = 6;
  public static final int COMMA = 39;
  public static final int OO = 10;
  public static final int DIV = 5;
  public static final int RP = 7;
  public static final int DIGIT = 12;
  public static final int PLUS = 2;
  public static final int MAIN = 37;
  public static final int IF = 20;
  public static final int ID = 8;
  public static final int LE = 14;
  public static final int EOF = 0;
  public static final int RETURN = 38;
  public static final int error = 1;
  public static final int MUL = 4;
  public static final int MOD = 11;
  public static final int BREAK = 34;
  public static final int VOID = 36;
  public static final int EQ = 18;
  public static final int LCB = 21;
  public static final int SWITCH = 26;
  public static final int COLON = 33;
  public static final int ELSE = 25;
  public static final int EE = 13;
  public static final int WHILE = 31;
  public static final int NE = 19;
  public static final int DEF = 35;
  public static final int DT = 24;
  public static final int RCB = 22;
  public static final int AO = 9;
  public static final int GR = 16;
  public static final int DO = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "LP",
  "RP",
  "ID",
  "AO",
  "OO",
  "MOD",
  "DIGIT",
  "EE",
  "LE",
  "GE",
  "GR",
  "LS",
  "EQ",
  "NE",
  "IF",
  "LCB",
  "RCB",
  "SM",
  "DT",
  "ELSE",
  "SWITCH",
  "FOR",
  "DECR",
  "INCR",
  "DO",
  "WHILE",
  "CASE",
  "COLON",
  "BREAK",
  "DEF",
  "VOID",
  "MAIN",
  "RETURN",
  "COMMA"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[15]=new String("GE");
		TT[23]=new String("SM");
		TT[32]=new String("CASE");
		TT[28]=new String("DECR");
		TT[29]=new String("INCR");
		TT[27]=new String("FOR");
		TT[3]=new String("MINUS");
		TT[17]=new String("LS");
		TT[6]=new String("LP");
		TT[39]=new String("COMMA");
		TT[10]=new String("OO");
		TT[5]=new String("DIV");
		TT[7]=new String("RP");
		TT[12]=new String("DIGIT");
		TT[2]=new String("PLUS");
		TT[37]=new String("MAIN");
		TT[20]=new String("IF");
		TT[8]=new String("ID");
		TT[14]=new String("LE");
		TT[0]=new String("EOF");
		TT[38]=new String("RETURN");
		TT[1]=new String("error");
		TT[4]=new String("MUL");
		TT[11]=new String("MOD");
		TT[34]=new String("BREAK");
		TT[36]=new String("VOID");
		TT[18]=new String("EQ");
		TT[21]=new String("LCB");
		TT[26]=new String("SWITCH");
		TT[33]=new String("COLON");
		TT[25]=new String("ELSE");
		TT[13]=new String("EE");
		TT[31]=new String("WHILE");
		TT[19]=new String("NE");
		TT[35]=new String("DEF");
		TT[24]=new String("DT");
		TT[22]=new String("RCB");
		TT[9]=new String("AO");
		TT[16]=new String("GR");
		TT[30]=new String("DO");
	}
public String getTT(int i){return TT[i];}
}

